
# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
primary_default: &primary_default
  adapter: postgresql
  encoding: unicode
  host: <%= Figaro.env.db_host %>
  database: <%= Figaro.env.db_name %>
  username: <%= Figaro.env.db_username %>
  password: <%= Figaro.env.db_password %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    <<: *primary_default
    database: <%= Figaro.env.db_name %>_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  primary:
    <<: *primary_default
    database: <%= Figaro.env.db_name %>_test

staging:
  primary:
    <<: *primary_default
    database: <%= Figaro.env.db_name %>_staging

production:
  primary:
    <<: *primary_default
    database: <%= Figaro.env.db_name %>_production