openapi: "3.0.1"
info:
  $ref: 'app/info/summary.yml'
servers:
  - url: http://localhost{3000}/app
    description: Optional localhost
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      format: JWT
      description: A JWT token is required to access this API
  responses:
    $ref: shared/errors.yml
#  parameters:
#    $ref: shared/parameters.yml
security:
  - BearerAuth: []
paths:
  # Sign up Routes
  /sign_up:
    $ref: app/sign_up/sign_up_person.yml
  # Users Routes
  /users:
    $ref: app/users/users.yml
tags:
  - name: Users
  - name: Sign Up
